[private_chef]
ip_mode="ipv4"
fips_enabled=false

[lager]
lager_console_backend="info"
error_logger_hwm=50

[oc_chef_wm]
api_version=""
server_flavor=""
default_orgname="test"
listen_ip="0.0.0.0"
port=1234
auth_skew=""
bulk_fetch_data_size=""
root_metric_key=""
authz_timeout=""
authz_fanout=""
reindex_batch_size=""
enable_actions=""
node_license=""
upgrade_url=""
actions_host=""
actions_port=""
actions_vhost=""
actions_exchange=""
actions_fqdn=""
max_request_size=""
server_version=""
health_ping_timeout=""
search_provider=""
base_resource_url=""
bulk_fetch_batch_size=""
strict_search_result_acls=""

[oc_chef_wm.rabbitmq.management]
user=""
port=""
timeout=""
init_count=""
max_count=""
cull_interval=""
max_age=""
max_connection_duration=""
ibrowse_options=""

[oc_chef_wm.rabbitmq.monitoring]
queue_length_monitor_enabled=""
queue_length_monitor_vhost=""
queue_length_monitor_millis=""
queue_length_monitor_timeout_millis=""
drop_on_full_capacity=""
prevent_erchef_startup_on_full_capacity=""
queue_at_capacity_affects_overall_status=""

[chef_authn]

[oc_chef_authz]

[chef_db]

[chef_index]

[chef_objects]

[data_collector]
enabled=false

[stats_hero]

[opscodeerl_httpc]
pooler_timeout=""

[sqerl]
db_host="localhost"
db_port=5432
db_user="opscode_chef"
db_pass=""
db_name="opscode_chef"
db_pooler_timeout=2000
sql_db_timeout=5000

[webmachine]

[ibrowse]
default_max_sessions=""
default_max_pipeline_size=""

[pooler.sqerl]
max_count=100
init_count=25
queue_max=200

[pooler.chef_depsolver]
max_count=100
init_count=25
queue_max=200
