[private_chef]
ip_mode="ipv4"
fips_enabled=false

[lager]
lager_console_backend="info"
error_logger_hwm=50

[oc_chef_wm]
api_version="12.0.0"
listen_ip="0.0.0.0"
port=8000
auth_skew=900
bulk_fetch_data_size=5
reindex_batch_size=10
node_license=999999
max_request_size=1000000
server_version=""
bulk_fetch_batch_size=5
strict_search_result_acls=false

[chef_authn]
keygen_cache_workers=10
keygen_cache_size=10
keygen_start_size=0
keygen_timeout=5000

[oc_chef_authz]

[chef_db]

[chef_index]

[chef_objects]

[data_collector]
enabled=false
server="automate-server.test"
port="443"

[stats_hero]

[opscodeerl_httpc]
pooler_timeout=""

[sqerl]
db_host="localhost"
db_port=5432
db_user="opscode_chef"
db_pass=""
db_name="opscode_chef"
db_pooler_timeout=2000
sql_db_timeout=5000

[webmachine]

[ibrowse]
default_max_sessions=""
default_max_pipeline_size=""

[pooler.sqerl]
max_count=100
init_count=20
queue_max=20

[pooler.chef_depsolver]
max_count=5
init_count=5
queue_max=50

