port=4321

[lager]
lager_console_backend="info"

[bookshelf]
listen_ip="0.0.0.0"
listen_port=4321
access_key_id="generated-by-default"
secret_access_key="generated-by-default"
storage_type="sql"
storage_type_sql=true
sql_retry_count=0
sql_retry_delay=10
abandoned_upload_cleanup_interval=1140000
deleted_data_cleanup_interval=420000
stream_download=true

[sqerl]
db_host="localhost"
db_port=5432
db_user="bookshelf"
db_pass=""
db_name="bookshelf"
db_pooler_timeout=2000
sql_db_timeout=5000

[pooler]
max_count=100
init_count=25
queue_max=200
