version: 2
updates:
- package-ecosystem: bundler
  directory: "/omnibus"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/omnibus/files/server-ctl-cookbooks/infra-server"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/oc-chef-pedant"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/src/chef-server-ctl"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/src/oc_bifrost/oc-bifrost-pedant"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/src/oc_bifrost"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/src/oc-id"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
