version: '3'
services:
  postgresql:
    image: chefdemo/postgresql:stable
    environment:
      HAB_POSTGRESQL: |
        [superuser]
        name = 'hab'
        password = 'chefrocks'
    volumes:
      - postgresql-data:/hab/svc/postgresql/data

  chef-server-ctl:
    image: $HAB_ORIGIN/chef-server-ctl
    command: --peer postgresql
    depends_on:
      - postgresql
    links:
      - postgresql

  elasticsearch:
    image: chefdemo/elasticsearch:stable
    command: --peer postgresql
    depends_on:
      - postgresql
    links:
      - postgresql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/hab/svc/elasticsearch/data

  oc_id:
    image: $HAB_ORIGIN/oc_id
    depends_on:
      - postgresql
    links:
      - postgresql
    command: --peer postgresql
      --bind database:postgresql.default
      --bind chef-server-ctl:chef-server-ctl.default

  bookshelf:
    image: $HAB_ORIGIN/bookshelf
    depends_on:
      - postgresql
    links:
      - postgresql
    environment:
      - FOO=bar
    command: --peer postgresql
      --bind database:postgresql.default
      --bind chef-server-ctl:chef-server-ctl.default

  oc_bifrost:
    image: $HAB_ORIGIN/oc_bifrost
    depends_on:
      - postgresql
    links:
      - postgresql
    environment:
      - FOO=bar
    command: --peer postgresql
      --bind database:postgresql.default
      --bind chef-server-ctl:chef-server-ctl.default

  oc_erchef:
    image: $HAB_ORIGIN/oc_erchef
    depends_on:
      - elasticsearch
      - oc_bifrost
      - postgresql
    links:
      - elasticsearch
      - oc_bifrost
      - postgresql
    environment:
      - FOO=bar
    volumes:
      - erchef-data:/hab/svc/oc_erchef/data
    command: --peer postgresql
      --bind bookshelf:bookshelf.default
      --bind oc_bifrost:oc_bifrost.default
      --bind database:postgresql.default
      --bind elasticsearch:elasticsearch.default
      --bind chef-server-ctl:chef-server-ctl.default

  chef-server-nginx:
    image: $HAB_ORIGIN/chef-server-nginx
    depends_on:
      - oc_erchef
      - oc_bifrost
      - oc_id
      - bookshelf
      - elasticsearch
      - postgresql
    links:
      - oc_erchef
      - oc_bifrost
      - oc_id
      - bookshelf
      - elasticsearch
      - postgresql
    environment:
      - FOO=bar
    command: --peer postgresql
      --bind oc_erchef:oc_erchef.default
      --bind oc_bifrost:oc_bifrost.default
      --bind oc_id:oc_id.default
      --bind bookshelf:bookshelf.default
      --bind elasticsearch:elasticsearch.default
    ports:
      - 80:8080
      - 443:8443

volumes:
  postgresql-data:
  elasticsearch-data:
  erchef-data:
