chef:
  endpoint: https://192.168.33.100
  superuser: pivotal
doorkeeper:
  administrators:
    - rainbowdash
email_from_address: 'Chef Notifications <notifications@chef.io>'
protocol: https
secret_key_base: CHANGE ME
zendesk:
  subdomain: getchef
